(defun matrix-mul (a b)
(let* (
		(m (nth 0 (array-dimensions a)))
		(s (nth 1 (array-dimensions a)))
		(n (nth 1 (array-dimensions b)))
		(result  (make-array (list m n)))
	)
(dotimes (i m) 
	(dotimes (j n)
		(setf (aref result i j) 0.0)
		(dotimes (k s)
			(incf (aref result i j) (* (aref a i k) (aref b k j))))
))
result
))